-- Removendo as tabelas existentes
DROP TABLE ID EXISTS banco CASCADE;
DROP TABLE ID EXISTS categoria CASCADE;
DROP TABLE ID EXISTS conta CASCADE;
DROP TABLE ID EXISTS meta CASCADE;
DROP TABLE ID EXISTS orcamento CASCADE;
DROP TABLE ID EXISTS tipo_conta CASCADE;
DROP TABLE ID EXISTS transacao CASCADE;
DROP TABLE ID EXISTS transacao_recorrente CASCADE;
DROP TABLE ID EXISTS usuario CASCADE;

-- Tabela de bancos disponíveis no sistema
CREATE TABLE banco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icone_url VARCHAR(255),
    nome VARCHAR(255)
);

-- Tabela de armazenar os usuários do sistema
CREATE TABLE usuario (
     id VARCHAR(255) PRIMARY KEY,
     email VARCHAR(255) NOT NULL UNIQUE,
     img_url VARCHAR(255),
     nome VARCHAR(255) NOT NULL,
     senha VARCHAR(255) NOT NULL
);

-- Tabela de categorias de receitas, despesas e metas
CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativa BOOLEAN DEFAULT TRUE NOT NULL,
    interna_sistema BOOLEAN DEFAULT FALSE NOT NULL,
    cor VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    tipo_categoria VARCHAR(255) CHECK (tipo_categoria IN ('RECEITA', 'DESPESA', 'META')),
    usuario_id VARCHAR(255) NOT NULL,
    UNIQUE (usuario_id, nome)
);

-- Tabela contas
CREATE TABLE conta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saldo_inicial NUMERIC(38,2) NOT NULL,
    banco_id BIGINT,
    tipo_conta_id BIGINT,
    descricao VARCHAR(255) NOT NULL,
    usuario_id VARCHAR(255) NOT NULL,
    UNIQUE (usuario_id, descricao)
);

-- Tabela de metas
CREATE TABLE meta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progresso NUMERIC(38,2),
    valor_investido NUMERIC(38,2) NOT NULL,
    valor_meta NUMERIC(38,2) NOT NULL,
    comentario VARCHAR(255),
    descricao VARCHAR(255) NOT NULL,
    url_img VARCHAR(255),
    usuario_id VARCHAR(255) NOT NULL,
    UNIQUE (usuario_id, descricao)
);

-- Tabela de notificações de metas
CREATE TABLE notificacao_meta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificado BOOLEAN,
    threshold INTEGER,
    meta_id BIGINT
);

-- Tabela de notificações de orçamentos
CREATE TABLE notificacao_orcamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificado BOOLEAN NOT NULL,
    threshold INTEGER,
    orcamento_id BIGINT UNIQUE
);

-- Tabela de orçamentos
CREATE TABLE orcamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    progresso NUMERIC(38,2),
    valor_estimado NUMERIC(38,2) NOT NULL,
    valor_gasto NUMERIC(38,2),
    valor_restante NUMERIC(38,2),
    categoria_id BIGINT NOT NULL,
    descricao VARCHAR(255),
    usuario_id VARCHAR(255) NOT NULL,
    UNIQUE (usuario_id, mes, ano, categoria_id)
);

-- Tabela dos tipos de contas
CREATE TABLE tipo_conta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_conta VARCHAR(255) CHECK (tipo_conta IN ('CONTA_CORRENTE', 'CARTEIRA', 'POUPANCA', 'INVESTIMENTOS', 'OUTRO'))
);

-- Tabela de transações
CREATE TABLE transacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    valor NUMERIC(38,2) NOT NULL,
    categoria_id BIGINT NOT NULL,
    conta_origem BIGINT NOT NULL,
    transacao_recorrente_id BIGINT,
    comentario TEXT,
    descricao TEXT NOT NULL,
    origem_transacao VARCHAR(255) CHECK (origem_transacao IN ('NORMAL', 'FIXA', 'PARCELADA')),
    tipo VARCHAR(255) NOT NULL CHECK (tipo IN ('RECEITA', 'DESPESA', 'META')),
    usuario_id VARCHAR(255) NOT NULL
);

-- Tabela de transacoes de metas
CREATE TABLE transacao_meta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_id BIGINT NOT NULL,
    transacao_id BIGINT NOT NULL UNIQUE
);

-- Tabela de transações recorrentes
CREATE TABLE transacao_recorrente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativa BOOLEAN DEFAULT TRUE NOT NULL,
    data_cadastro DATE NOT NULL,
    data_final DATE,
    qtd_parcelas INTEGER,
    ultima_execucao DATE,
    valor NUMERIC(38,2) NOT NULL,
    categoria_id BIGINT NOT NULL,
    conta_id BIGINT NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    periodicidade VARCHAR(255) NOT NULL CHECK (periodicidade IN ('DIARIO', 'SEMANAL', 'MENSAL', 'ULTIMO_DIA_MES')),
    tipo VARCHAR(255) NOT NULL CHECK (tipo IN ('RECEITA', 'DESPESA', 'META')),
    tipo_repeticao VARCHAR(255) NOT NULL CHECK (tipo_repeticao IN ('FIXO', 'PARCELAMENTO')),
    usuario_id VARCHAR(255) NOT NULL
);


