-- Remover tabelas existentes para evitar conflitos
DROP TABLE IF EXISTS banco CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS conta CASCADE;
DROP TABLE IF EXISTS meta CASCADE;
DROP TABLE IF EXISTS orcamento CASCADE;
DROP TABLE IF EXISTS tipo_conta CASCADE;
DROP TABLE IF EXISTS transacao CASCADE;
DROP TABLE IF EXISTS transacao_recorrente CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

-- Tabela banco
CREATE TABLE banco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icone_url VARCHAR(255),
    nome VARCHAR(255)
);

-- Tabela tipo_conta
CREATE TABLE tipo_conta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_conta VARCHAR(255) CHECK (tipo_conta IN ('CONTA_CORRENTE', 'CARTEIRA', 'POUPANCA', 'INVESTIMENTOS', 'OUTRO'))
);

-- Tabela usuario
CREATE TABLE usuario (
    id VARCHAR(255) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

-- Tabela conta
CREATE TABLE conta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saldo NUMERIC(38, 2),
    banco_id BIGINT,
    tipo_conta_id BIGINT,
    usuario_id VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    UNIQUE (usuario_id, descricao)
);

-- Tabela categoria
CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativa BOOLEAN DEFAULT TRUE NOT NULL,
    interna_sistema BOOLEAN DEFAULT FALSE NOT NULL,
    cor VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    tipo_categoria VARCHAR(255) CHECK (tipo_categoria IN ('RECEITA', 'DESPESA')),
    usuario_id VARCHAR(255) NOT NULL,
    UNIQUE (usuario_id, nome)
);

-- Tabela transacao
CREATE TABLE transacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor NUMERIC(38, 2) NOT NULL,
    data DATE NOT NULL,
    descricao TEXT NOT NULL,
    tipo VARCHAR(255) NOT NULL CHECK (tipo IN ('RECEITA', 'DESPESA')),
    categoria_id BIGINT NOT NULL,
    conta_origem BIGINT NOT NULL,
    usuario_id VARCHAR(255) NOT NULL,
    comentario TEXT,
    transacao_fixa_id BIGINT
);

-- Tabela transacao_recorrente
CREATE TABLE transacao_recorrente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_cadastro DATE NOT NULL,
    data_final DATE,
    qtd_parcelas INTEGER,
    tipo_repeticao SMALLINT NOT NULL CHECK (tipo_repeticao BETWEEN 0 AND 1),
    ultima_execucao DATE,
    valor NUMERIC(38, 2) NOT NULL,
    categoria_id BIGINT NOT NULL,
    conta_id BIGINT NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    periodicidade VARCHAR(255) NOT NULL CHECK (periodicidade IN ('DIARIO', 'SEMANAL', 'MENSAL', 'ULTIMO_DIA_MES')),
    tipo VARCHAR(255) NOT NULL CHECK (tipo IN ('RECEITA', 'DESPESA')),
    usuario_id VARCHAR(255) NOT NULL
);

-- Tabela meta
CREATE TABLE meta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_investido NUMERIC(38, 2) NOT NULL,
    valor_meta NUMERIC(38, 2) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    url_img VARCHAR(255),
    usuario_id VARCHAR(255) NOT NULL,
    UNIQUE (usuario_id, descricao)
);

-- Tabela orcamento
CREATE TABLE orcamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    valor_estimado NUMERIC(38, 2) NOT NULL,
    valor_gasto NUMERIC(38, 2),
    valor_restante NUMERIC(38, 2),
    categoria_id BIGINT NOT NULL,
    descricao VARCHAR(255),
    usuario_id VARCHAR(255) NOT NULL,
    UNIQUE (usuario_id, mes, ano, categoria_id)
);