version: "3.7"
services:
# ====================================================================================================================
# POSTGRES SERVER
# ====================================================================================================================
  pg-docker:
    image: postgres:14-alpine
    container_name: mb-postgresql-server
    environment:
      - POSTGRES_DB=meubolso
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
    ports:
      - 5433:5432
    volumes:
      - ./src/main/resources/create.sql:/docker-entrypoint-initdb.d/create.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network

# ====================================================================================================================
# PGADMIN
# ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4:latest
    container_name: mb-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234567
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network

# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge

# ======================================================================================================================
# VOLUMES
# ======================================================================================================================
volumes:
  pgdata:
    driver: local
  pgadmindata:
    driver: local