version: "3.7"
services:
# ====================================================================================================================
# POSTGRES SERVER
# ====================================================================================================================
  pg-docker:
    image: postgres:14-alpine
    container_name: mb-postgresql-server
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network

# ====================================================================================================================
# PGADMIN
# ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4:latest
    container_name: mb-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network

# ====================================================================================================================
# APLICAÇÃO
# ====================================================================================================================
  application-docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: mb-api
    depends_on:
      - pg-docker
      - pgadmin-docker
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTICE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - dev-network

# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge

# ======================================================================================================================
# VOLUMES
# ======================================================================================================================
volumes:
  pgdata:
    driver: local
  pgadmindata:
    driver: local