create table banco (id bigint generated by default as identity, icone_url varchar(255), nome varchar(255), primary key (id));
create table categoria (ativa boolean default true not null, interna_sistema boolean default false not null, id bigint generated by default as identity, cor varchar(255) not null, nome varchar(255) not null, tipo_categoria varchar(255) check (tipo_categoria in ('RECEITA','DESPESA','META')), usuario_id varchar(255) not null, primary key (id), unique (usuario_id, nome));
create table conta (saldo_inicial numeric(38,2) not null, banco_id bigint, id bigint generated by default as identity, tipo_conta_id bigint, descricao varchar(255) not null, usuario_id varchar(255) not null, primary key (id), unique (usuario_id, descricao));
create table meta (progresso numeric(38,2), valor_investido numeric(38,2) not null, valor_meta numeric(38,2) not null, id bigint generated by default as identity, comentario varchar(255), descricao varchar(255) not null, url_img varchar(255), usuario_id varchar(255) not null, primary key (id), unique (usuario_id, descricao));
create table notificacao_meta (notificado boolean, threshold integer, id bigint generated by default as identity, meta_id bigint, primary key (id));
create table notificacao_orcamento (notificado boolean not null, threshold integer, id bigint generated by default as identity, orcamento_id bigint unique, primary key (id));
create table orcamento (ano integer not null, mes integer not null, progresso numeric(38,2), valor_estimado numeric(38,2) not null, valor_gasto numeric(38,2), valor_restante numeric(38,2), categoria_id bigint not null, id bigint generated by default as identity, descricao varchar(255), usuario_id varchar(255) not null, primary key (id), unique (usuario_id, mes, ano, categoria_id));
create table tipo_conta (id bigint generated by default as identity, tipo_conta varchar(255) check (tipo_conta in ('CONTA_CORRENTE','CARTEIRA','POUPANCA','INVESTIMENTOS','OUTRO')), primary key (id));
create table transacao (data DATE not null, valor numeric(38,2) not null, categoria_id bigint not null, conta_origem bigint not null, id bigint generated by default as identity, transacao_recorrente_id bigint, comentario TEXT, descricao TEXT not null, origem_transacao varchar(255) check (origem_transacao in ('NORMAL','FIXA','PARCELADA')), tipo varchar(255) not null check (tipo in ('RECEITA','DESPESA','META')), usuario_id varchar(255) not null, primary key (id));
create table transacao_meta (id bigint generated by default as identity, meta_id bigint not null, transacao_id bigint not null unique, primary key (id));
create table transacao_recorrente (ativa boolean default true not null, data_cadastro DATE not null, data_final date, qtd_parcelas integer, ultima_execucao date, valor numeric(38,2) not null, categoria_id bigint not null, conta_id bigint not null, id bigint generated by default as identity, descricao varchar(255) not null, periodicidade varchar(255) not null check (periodicidade in ('DIARIO','SEMANAL','MENSAL','ULTIMO_DIA_MES')), tipo varchar(255) not null check (tipo in ('RECEITA','DESPESA','META')), tipo_repeticao varchar(255) not null check (tipo_repeticao in ('FIXO','PARCELAMENTO')), usuario_id varchar(255) not null, primary key (id));
create table usuario (email varchar(255) not null unique, id varchar(255) not null, img_url varchar(255), nome varchar(255) not null, senha varchar(255) not null, primary key (id));

-- CATEGORIA
alter table if exists categoria
    add constraint fk_categoria_usuario
    foreign key (usuario_id)
    references usuario;

-- CONTA
alter table if exists conta
    add constraint fk_conta_banco
    foreign key (banco_id)
    references banco
    on delete cascade;

alter table if exists conta
    add constraint fk_conta_tipo_conta
    foreign key (tipo_conta_id)
    references tipo_conta;

alter table if exists conta
    add constraint fk_conta_usuario
    foreign key (usuario_id)
    references usuario;

-- META
alter table if exists meta
    add constraint fk_meta_usuario
    foreign key (usuario_id)
    references usuario;

-- NOTIFICACAO_META
alter table if exists notificacao_meta
    add constraint fk_notificacao_meta_meta
    foreign key (meta_id)
    references meta;

-- NOTIFICACAO_ORCAMENTO
alter table if exists notificacao_orcamento
    add constraint fk_notificacao_orcamento_orcamento
    foreign key (orcamento_id)
    references orcamento;

-- ORCAMENTO
alter table if exists orcamento
    add constraint fk_orcamento_categoria
    foreign key (categoria_id)
    references categoria;

alter table if exists orcamento
    add constraint fk_orcamento_usuario
    foreign key (usuario_id)
    references usuario;

-- TRANSACAO
alter table if exists transacao
    add constraint fk_transacao_categoria
    foreign key (categoria_id)
    references categoria;

alter table if exists transacao
    add constraint fk_transacao_conta_origem
    foreign key (conta_origem)
    references conta;

alter table if exists transacao
    add constraint fk_transacao_transacao_recorrente
    foreign key (transacao_recorrente_id)
    references transacao_recorrente;

alter table if exists transacao
    add constraint fk_transacao_usuario
    foreign key (usuario_id)
    references usuario;

-- TRANSACAO_META
alter table if exists transacao_meta
    add constraint fk_transacao_meta_meta
    foreign key (meta_id)
    references meta;

alter table if exists transacao_meta
    add constraint fk_transacao_meta_transacao
    foreign key (transacao_id)
    references transacao;

-- TRANSACAO_RECORRENTE
alter table if exists transacao_recorrente
    add constraint fk_transacao_recorrente_categoria
    foreign key (categoria_id)
    references categoria;

alter table if exists transacao_recorrente
    add constraint fk_transacao_recorrente_conta
    foreign key (conta_id)
    references conta;

alter table if exists transacao_recorrente
    add constraint fk_transacao_recorrente_usuario
    foreign key (usuario_id)
    references usuario;

insert into tipo_conta(id, tipo_conta) values ('1', 'CONTA_CORRENTE');
insert into tipo_conta(id, tipo_conta) values ('2', 'CARTEIRA');
insert into tipo_conta(id, tipo_conta) values ('3', 'POUPANCA');
insert into tipo_conta(id, tipo_conta) values ('4', 'INVESTIMENTOS');
insert into tipo_conta(id, tipo_conta) values ('5', 'OUTRO');

insert into banco (nome, icone_url) values ('Banco do Brasil', 'https://drive.google.com/file/d/175Zxd1rNpYApB6UN6etYy5LUw1FnJAcr/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Banrisul', 'https://drive.google.com/file/d/1JlI6arEc4JdGgGX40Qg9aakVTCeCdx1N/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Bradesco', 'https://drive.google.com/file/d/1cQy20YwrEe2cSaGgVEOT1WYrfK0GBAc0/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Banco de Brasília', 'https://drive.google.com/file/d/1LdO9fizwyfBq4GFKfwFRC1DbfmweLjv6/view?usp=drive_link');
insert into banco (nome, icone_url) values ('C6-Bank', 'https://drive.google.com/file/d/17GU6LsvVWAFJY-rsQo8utmsD_oB4WlK5/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Caixa Econômica', 'https://drive.google.com/file/d/1xHzud3kvwJgikLX4tux7imkdNZcFxhik/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Inter', 'https://drive.google.com/file/d/1DIjWq9DdLap6uTUw2kWJdFLJdkZ7dOxG/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Itaú', 'https://drive.google.com/file/d/1KLex9fKzbu61e_Tc_iVTh--V8abkEmvN/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Mercado Pago', 'https://drive.google.com/file/d/1HXSGreKetuOtslS4R8-OOThliEfzvsLE/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Neon', 'https://drive.google.com/file/d/1K6SmPZNJR3XbGRGdYVuU0knl33jva8LK/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Next', 'https://drive.google.com/file/d/1IRpu69uNs0AnHLDB72JGHv-99GGNL44j/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Nubank', 'https://drive.google.com/file/d/1I94WYYVGjnTFYG__kbYNmscNt4xd0IfU/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Original', 'https://drive.google.com/file/d/1P7kplxYk3OBxlMq5AuHg4WIGR-QRFhc-/view?usp=drive_link');
insert into banco (nome, icone_url) values ('PagBank', 'https://drive.google.com/file/d/10ycX-rHNTUNJ7SRlH_juj9YPIUuZWm4c/view?usp=drive_link');
insert into banco (nome, icone_url) values ('PayPal', 'https://drive.google.com/file/d/1ulKwls7GveOkkT5V7i-YCR6ye1-eCqpC/view?usp=drive_link');
insert into banco (nome, icone_url) values ('PicPay', 'https://drive.google.com/file/d/190BdT7ORmJTIXdw6ZX6XCJFkCp3dn53a/view?usp=drive_link');
insert into banco (nome, icone_url) values ('Santander', 'https://drive.google.com/file/d/1_upjxBvX69yejfUPsu6g1BfdUmndcsEe/view?usp=drive_link');

